# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
  
        MainWindow.resize(606, 478)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QLabel#label_3{\n"
"    color:grey;\n"
"    font:12pt;\n"
"}\n"
"QLabel#label_4{\n"
"    color:rgba(0,0,0,105);\n"
"    font:25pt;\n"
"}\n"
"QLabel#signature{\n"
"    color:rgba(0,0,0,105);\n"
"    font:30pt;\n"
"}\n"
"QLabel#label{\n"
"    background-color: qlineargradient(spread:pad, x1:0.472045, y1:0, x2:0.556818, y2:0.744, stop:0 rgba(85, 68, 112,255), stop:1 rgba(255, 112,143, 255));\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton#Start,#End{\n"
"    border-radius:10px;\n"
"    background-color: rgba(190, 155, 255,255);\n"
"    color:rgba(0,0,0,255);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton#Start:hover,#End:hover{\n"
"    color:rgba(255,255,200,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(187, 100, 229, 255), stop:1 rgba(255, 155, 255, 255));\n"
"    border-radius:10px;\n"
"    }\n"
"QPushButton#Start:pressed,#End:pressed{\n"
"    border-radius:10px;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#Closed{\n"
"    background-color: rgba(0, 0,0, 0);\n"
"    color:rgba(120,115,255,255);\n"
"    \n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#Closed:hover{\n"
"    color:rgba(250,223,11,255);\n"
"}\n"
"QPushButton#Closed:pressed{\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"\n"
"QPushButton#fButton,#iButton,#tButton{\n"
"    background-color: rgba(0, 0,0, 0);\n"
"    color:rgba(120,215,255,255);\n"
"    \n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#fButton:hover,#iButton:hover,#tButton:hover{\n"
"    color:rgba(250,223,11,255);\n"
"}\n"
"QPushButton#fButton:pressed,#iButton:pressed,#tButton:pressed{\n"
"    padding-left:1px;\n"
"    padding-top:1px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QLineEdit#Search{\n"
"    background-color:rgba(0,0,0,0);\n"
"    border:2px solid rgba(0,0,0,0);\n"
"    border-bottom-color: rgba(1,100,100,255);\n"
"    color:rgb(0,0,0);\n"
"    padding-bottom:7px;\n"
"}\n"
"QHBoxLayout#horizontalLayout{\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QFrame#SEARCH{\n"
"    background-color: rgba(255, 255, 255,255);\n"
"    border-radius : 25px;\n"
"}\n"
"QPushButton#btn_search{\n"
"    border-radius:10px;\n"
"    background-color: rgba(190, 155, 255,255);\n"
"    color:rgba(0,0,0,255);\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton#btn_search:hover{\n"
"    color:rgba(255,255,200,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(187, 100, 229, 255), stop:1 rgba(255, 155, 255, 255));\n"
"    border-radius:10px;\n"
"    }\n"
"QPushButton#btn_search:pressed{\n"
"    border-radius:10px;\n"
"    padding-left:2px;\n"
"    padding-top:2px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.SEARCH = QtWidgets.QFrame(self.centralwidget)
        self.SEARCH.setGeometry(QtCore.QRect(290, 40, 16, 330))
        self.SEARCH.setStyleSheet("")
        self.SEARCH.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SEARCH.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SEARCH.setObjectName("SEARCH")
        self.label_3 = QtWidgets.QLabel(self.SEARCH)
        self.label_3.setGeometry(QtCore.QRect(60, 28, 150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(0)
        self.label_3.setStyleSheet("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.Search = QtWidgets.QLineEdit(self.SEARCH)
        self.Search.setGeometry(QtCore.QRect(40, 60, 200, 40))
        self.Search.setStyleSheet("")
        self.Search.setText("")
        self.Search.setClearButtonEnabled(True)
        self.Search.setObjectName("Search")
        self.label_6 = QtWidgets.QLabel(self.SEARCH)
        self.label_6.setGeometry(QtCore.QRect(30, 138, 50, 30))
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.SEARCH)
        self.label_11.setGeometry(QtCore.QRect(30, 168, 50, 30))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.SEARCH)
        self.label_12.setGeometry(QtCore.QRect(30, 228, 50, 30))
        self.label_12.setObjectName("label_12")
        self.label_8 = QtWidgets.QLabel(self.SEARCH)
        self.label_8.setGeometry(QtCore.QRect(30, 198, 50, 30))
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.SEARCH)
        self.label_13.setGeometry(QtCore.QRect(30, 288, 50, 30))
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.SEARCH)
        self.label_9.setGeometry(QtCore.QRect(30, 258, 50, 30))
        self.label_9.setObjectName("label_9")
        self.Code = QtWidgets.QLabel(self.SEARCH)
        self.Code.setGeometry(QtCore.QRect(80, 138, 165, 30))
        self.Code.setWordWrap(True)
        self.Code.setObjectName("Code")
        self.Name = QtWidgets.QLabel(self.SEARCH)
        self.Name.setGeometry(QtCore.QRect(80, 168, 170, 30))
        self.Name.setWordWrap(True)
        self.Name.setObjectName("Name")
        self.Low = QtWidgets.QLabel(self.SEARCH)
        self.Low.setGeometry(QtCore.QRect(80, 228, 165, 30))
        self.Low.setWordWrap(True)
        self.Low.setObjectName("Low")
        self.High = QtWidgets.QLabel(self.SEARCH)
        self.High.setGeometry(QtCore.QRect(80, 198, 165, 30))
        self.High.setWordWrap(True)
        self.High.setObjectName("High")
        self.Volume = QtWidgets.QLabel(self.SEARCH)
        self.Volume.setGeometry(QtCore.QRect(80, 288, 165, 30))
        self.Volume.setWordWrap(True)
        self.Volume.setObjectName("Volume")
        self.Close = QtWidgets.QLabel(self.SEARCH)
        self.Close.setGeometry(QtCore.QRect(80, 258, 165, 30))
        self.Close.setWordWrap(True)
        self.Close.setObjectName("Close")
        self.btn_search = QtWidgets.QPushButton(self.SEARCH)
        self.btn_search.setGeometry(QtCore.QRect(100, 110, 90, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("")
        self.btn_search.setObjectName("btn_search")
        self.progressBar = QtWidgets.QProgressBar(self.SEARCH)
        self.progressBar.setGeometry(QtCore.QRect(48, 136, 180, 2))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 40, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(124, 320, 90, 30))
        self.Start.setStyleSheet("")
        self.Start.setObjectName("Start")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 80, 230, 170))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.Closed = QtWidgets.QPushButton(self.centralwidget)
        self.Closed.setGeometry(QtCore.QRect(280, 40, 20, 20))
        self.Closed.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Closed.setFont(font)
        self.Closed.setObjectName("Closed")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 280, 160, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.fButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(19)
        self.fButton.setFont(font)
        self.fButton.setStyleSheet("")
        self.fButton.setObjectName("fButton")
        self.horizontalLayout.addWidget(self.fButton)
        self.tButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.tButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(19)
        self.tButton.setFont(font)
        self.tButton.setStyleSheet("")
        self.tButton.setObjectName("tButton")
        self.horizontalLayout.addWidget(self.tButton)
        self.iButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.iButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(19)
        self.iButton.setFont(font)
        self.iButton.setStyleSheet("")
        self.iButton.setObjectName("iButton")
        self.horizontalLayout.addWidget(self.iButton)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 240, 200, 41))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color:black;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.End = QtWidgets.QPushButton(self.centralwidget)
        self.End.setGeometry(QtCore.QRect(124, 320, 90, 30))
        self.End.setStyleSheet("")
        self.End.setObjectName("End")
        self.update = QtWidgets.QLabel(self.centralwidget)
        self.update.setGeometry(QtCore.QRect(100, 360, 136, 13))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(6)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setText("")
        self.update.setAlignment(QtCore.Qt.AlignCenter)
        self.update.setWordWrap(True)
        self.update.setObjectName("update")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 80, 230, 170))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.signature = QtWidgets.QLabel(self.centralwidget)
        self.signature.setGeometry(QtCore.QRect(60, 200, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Road Sunshine")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.signature.setFont(font)
        self.signature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.signature.setObjectName("signature")
        self.SEARCH.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.Start.raise_()
        self.label_5.raise_()
        self.Closed.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_7.raise_()
        self.End.raise_()
        self.update.raise_()
        self.label_10.raise_()
        self.signature.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "NasDaq Search"))
        self.Search.setWhatsThis(_translate("MainWindow", "Search NasDaq Codes"))
        self.Search.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Code    :</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Name  :</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Low :</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">High :</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Volume :</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Close :</p></body></html>"))
        self.Code.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Name.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Low.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.High.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Volume.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Close.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_search.setText(_translate("MainWindow", "SEARCH"))
        self.label_4.setText(_translate("MainWindow", "NasDaq"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>My name is Surenjanath Singh.<br/>I\'ve learnt to code in python on my free time using youtube, udemy and my curiousity. <br/>I\'ve always wanted to learn and master such lovely language.<br/>I dare you to take up a programming language. It would make your life easy and fun especially when you are dealing with data. Data is life.<br/><br/>Yours Sincerely,</p></body></html>"))
        self.Closed.setText(_translate("MainWindow", "X"))
        self.fButton.setText(_translate("MainWindow", "E"))
        self.tButton.setText(_translate("MainWindow", "D"))
        self.iButton.setText(_translate("MainWindow", "C"))
        self.label_7.setText(_translate("MainWindow", "Follow me on "))
        self.End.setText(_translate("MainWindow", "End"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Program Version : 1.0<br/>Created by <span style=\" font-style:italic;\">Surenjanath Singh</span></p><p>Last Updated : 3rd July 2021<span style=\" font-style:italic;\"><br/><br/></span>Nasdaq is a user interface that one can use to search for information on a stock on a daily basis.<br/>It scrapes the internet for the data and then would display it to you according to your search.<br/>See more information in documentation.</p></body></html>"))
        self.signature.setText(_translate("MainWindow", "<html><head/><body><p>Surenjanath Singh</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
